### ISSUE TITLE
Feature: User can search for an anime

### ISSUE THREAD

**Issue by dn-phuong** [dn-phuong/ajax-project#1]
## ⚙️ Feature

User can search for an anime.

## 📐 Functionality

The user can type keywords into the search bar to find an anime.

## 🖼️ Wireframes

<img width="799" alt="Screen Shot 2022-03-03 at 9 53 44 PM" src="https://user-images.githubusercontent.com/93227069/156707971-3b73fcfa-3e62-4d45-8d88-3e208ee93831.png">

<img width="1427" alt="Screen Shot 2022-03-03 at 9 56 10 PM" src="https://user-images.githubusercontent.com/93227069/156707975-057a21eb-ff92-4116-a586-d60c620177d1.png">

## ✅ Task List

- [ ] Create search form.
- [ ] Ensure the form looks nice on both mobile-sized and desktop-sized screens.
- [ ] Make input for search form required.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
